name: CI

on:
  push:
    branches: [ main ]
    paths:
      - 'Dockerfile'
      - 'go.*'
      - 'cmd/**'
      - 'internal/**'
      - '.github/workflows/**'

jobs:
  build:
    name: Build & Push to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: psidex/spacexlaunchbot-webserver:latest
